version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "fhir-encounters:1:1"
      GROUP_ID: api
    depends_on:
      - zookeeper
    networks:
      - my-network


  hapi-fhir:
    build: ./hapi-fhir-jpaserver-starter
    ports:
      - "8003:8080"
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres:15.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - hapiData:/var/lib/postgresql/data
    networks:
      - my-network

  consumer:
    build: ./fhir-kafka-listener
    ports:
      - "8002:8002"
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092
      - HAPI_FHIR_SERVER_HOST=hapi-fhir
      - HAPI_FHIR_SERVER_PORT=8080
    networks:
      - my-network

  producer:
    build: ./fhir-endpoints
    ports:
      - "8001:8001"
    depends_on:
      - kafka
      - consumer
      - hapi-fhir
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  hapiData: